import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link  from "next/link"
import { getSession, logout } from '@/lib';
import { redirect } from "next/navigation";
import Image from "next/image"
import KenCodeIcon from "@/public/KenCodeIcon.svg"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const KenCodeLogo = () => {
  return (
    <div className="logo">
      <Image
        src={KenCodeIcon} 
        alt="KenCode Logo" 
        width={50} 
        height={50} 
      />
      <span>KenCode</span>
    </div>
  );
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <KenCodeLogo />
          <div className="nav-links">
            {/* eslint-disable-next-line jsx-a11y/anchor-is-valid */}
            {/* <Link to="/">Home</Link> */}
            <div className="dropdown">
              <button className="dropbtn">Features</button>
              <div className="dropdown-content">
                {/* eslint-disable-next-line jsx-a11y/anchor-is-valid */}
                {/* <Link to="/deployments">Deployments</Link> */}
                {/* eslint-disable-next-line jsx-a11y/anchor-is-valid */}
                {/* <Link to="/collaboration">Collaboration</Link> */}
              </div>
            </div>
          </div>
          <div className="nav-actions">
            {!session ? (
              <>
                {/* eslint-disable-next-line jsx-a11y/anchor-is-valid */}
                <Link href="/signup" style={{ marginRight: '10px' }}>Signup</Link>
                {/* eslint-disable-next-line jsx-a11y/anchor-is-valid */}
                <Link href="/login">Login</Link>
              </>
            ) : (
              <form
                action={async () => {
                  "use server";
                  await logout();
                  redirect("/");
                }}
              >
                <button type="submit">Logout</button>
              </form>
            )}
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
